apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: {{ .Values.Name }}
    app.kubernetes.io/instance: {{ .Values.Name }}
    app.kubernetes.io/name: {{ .Values.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
  name: {{ .Values.Name }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.Name }}.{{ .Values.Domain }}
  ## YOUR CONFIGURATION HERE ##
